/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OpsRouteImport } from './routes/_ops'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as OpsIndexRouteImport } from './routes/_ops/index'
import { Route as OpsAccountsRouteImport } from './routes/_ops/accounts'
import { Route as OpsPoolRouteImport } from './routes/_ops/pool'
import { Route as OpsProvidersRouteImport } from './routes/_ops/providers'
import { Route as OpsScrapeRouteImport } from './routes/_ops/scrape'
import { Route as ApiInngestRouteImport } from './routes/api.inngest'
import { Route as ApiIptvShareRouteImport } from './routes/api.iptv-share'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/_ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAccountsRoute = OpsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPoolRoute = OpsPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => OpsRoute,
} as any)
const OpsProvidersRoute = OpsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsScrapeRoute = OpsScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => OpsRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvShareRoute = ApiIptvShareRouteImport.update({
  id: '/api/iptv-share',
  path: '/api/iptv-share',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OpsIndexRoute
  '/login': typeof AuthLoginRoute
  '/accounts': typeof OpsAccountsRoute
  '/pool': typeof OpsPoolRoute
  '/providers': typeof OpsProvidersRoute
  '/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-share': typeof ApiIptvShareRoute
}
export interface FileRoutesByTo {
  '/': typeof OpsIndexRoute
  '/login': typeof AuthLoginRoute
  '/accounts': typeof OpsAccountsRoute
  '/pool': typeof OpsPoolRoute
  '/providers': typeof OpsProvidersRoute
  '/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-share': typeof ApiIptvShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_ops': typeof OpsRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_ops/accounts': typeof OpsAccountsRoute
  '/_ops/pool': typeof OpsPoolRoute
  '/_ops/providers': typeof OpsProvidersRoute
  '/_ops/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-share': typeof ApiIptvShareRoute
  '/_ops/': typeof OpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/pool'
    | '/providers'
    | '/scrape'
    | '/api/inngest'
    | '/api/iptv-share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/pool'
    | '/providers'
    | '/scrape'
    | '/api/inngest'
    | '/api/iptv-share'
  id:
    | '__root__'
    | '/_auth'
    | '/_ops'
    | '/_auth/login'
    | '/_ops/accounts'
    | '/_ops/pool'
    | '/_ops/providers'
    | '/_ops/scrape'
    | '/api/inngest'
    | '/api/iptv-share'
    | '/_ops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiIptvShareRoute: typeof ApiIptvShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops': {
      id: '/_ops'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_ops/': {
      id: '/_ops/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/accounts': {
      id: '/_ops/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof OpsAccountsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/pool': {
      id: '/_ops/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof OpsPoolRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/providers': {
      id: '/_ops/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof OpsProvidersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/scrape': {
      id: '/_ops/scrape'
      path: '/scrape'
      fullPath: '/scrape'
      preLoaderRoute: typeof OpsScrapeRouteImport
      parentRoute: typeof OpsRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-share': {
      id: '/api/iptv-share'
      path: '/api/iptv-share'
      fullPath: '/api/iptv-share'
      preLoaderRoute: typeof ApiIptvShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OpsRouteChildren {
  OpsAccountsRoute: typeof OpsAccountsRoute
  OpsPoolRoute: typeof OpsPoolRoute
  OpsProvidersRoute: typeof OpsProvidersRoute
  OpsScrapeRoute: typeof OpsScrapeRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAccountsRoute: OpsAccountsRoute,
  OpsPoolRoute: OpsPoolRoute,
  OpsProvidersRoute: OpsProvidersRoute,
  OpsScrapeRoute: OpsScrapeRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiIptvShareRoute: ApiIptvShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
