/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OpsRouteImport } from './routes/_ops'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as OpsIndexRouteImport } from './routes/_ops/index'
import { Route as OpsAccountsRouteImport } from './routes/_ops/accounts'
import { Route as OpsDeepRefsRouteImport } from './routes/_ops/deep-refs'
import { Route as OpsPoolRouteImport } from './routes/_ops/pool'
import { Route as OpsProvidersRouteImport } from './routes/_ops/providers'
import { Route as OpsScrapeRouteImport } from './routes/_ops/scrape'
import { Route as ApiInngestRouteImport } from './routes/api.inngest'
import { Route as ApiIptvCatalogScrapeRouteImport } from './routes/api.iptv-catalog-scrape'
import { Route as ApiIptvCatalogVerifyRouteImport } from './routes/api.iptv-catalog-verify'
import { Route as ApiIptvShareRouteImport } from './routes/api.iptv-share'
import { Route as ApiIptvPasteBodyRouteImport } from './routes/api.iptv-paste-body'
import { Route as ApiIptvDeepRefReprocessRouteImport } from './routes/api.iptv-deep-ref-reprocess'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginMfaRouteImport } from './routes/_auth/login.mfa'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/_ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAccountsRoute = OpsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDeepRefsRoute = OpsDeepRefsRouteImport.update({
  id: '/deep-refs',
  path: '/deep-refs',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPoolRoute = OpsPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => OpsRoute,
} as any)
const OpsProvidersRoute = OpsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsScrapeRoute = OpsScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => OpsRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvCatalogScrapeRoute = ApiIptvCatalogScrapeRouteImport.update({
  id: '/api/iptv-catalog-scrape',
  path: '/api/iptv-catalog-scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvCatalogVerifyRoute = ApiIptvCatalogVerifyRouteImport.update({
  id: '/api/iptv-catalog-verify',
  path: '/api/iptv-catalog-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvShareRoute = ApiIptvShareRouteImport.update({
  id: '/api/iptv-share',
  path: '/api/iptv-share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvPasteBodyRoute = ApiIptvPasteBodyRouteImport.update({
  id: '/api/iptv-paste-body',
  path: '/api/iptv-paste-body',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvDeepRefReprocessRoute = ApiIptvDeepRefReprocessRouteImport.update({
  id: '/api/iptv-deep-ref-reprocess',
  path: '/api/iptv-deep-ref-reprocess',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginMfaRoute = AuthLoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OpsIndexRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/accounts': typeof OpsAccountsRoute
  '/deep-refs': typeof OpsDeepRefsRoute
  '/pool': typeof OpsPoolRoute
  '/providers': typeof OpsProvidersRoute
  '/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-catalog-scrape': typeof ApiIptvCatalogScrapeRoute
  '/api/iptv-catalog-verify': typeof ApiIptvCatalogVerifyRoute
  '/api/iptv-share': typeof ApiIptvShareRoute
  '/api/iptv-paste-body': typeof ApiIptvPasteBodyRoute
  '/api/iptv-deep-ref-reprocess': typeof ApiIptvDeepRefReprocessRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/mfa': typeof AuthLoginMfaRoute
}
export interface FileRoutesByTo {
  '/': typeof OpsIndexRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/accounts': typeof OpsAccountsRoute
  '/deep-refs': typeof OpsDeepRefsRoute
  '/pool': typeof OpsPoolRoute
  '/providers': typeof OpsProvidersRoute
  '/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-catalog-scrape': typeof ApiIptvCatalogScrapeRoute
  '/api/iptv-catalog-verify': typeof ApiIptvCatalogVerifyRoute
  '/api/iptv-share': typeof ApiIptvShareRoute
  '/api/iptv-paste-body': typeof ApiIptvPasteBodyRoute
  '/api/iptv-deep-ref-reprocess': typeof ApiIptvDeepRefReprocessRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/mfa': typeof AuthLoginMfaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_ops': typeof OpsRouteWithChildren
  '/_auth/login': typeof AuthLoginRouteWithChildren
  '/_ops/accounts': typeof OpsAccountsRoute
  '/_ops/deep-refs': typeof OpsDeepRefsRoute
  '/_ops/pool': typeof OpsPoolRoute
  '/_ops/providers': typeof OpsProvidersRoute
  '/_ops/scrape': typeof OpsScrapeRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/iptv-catalog-scrape': typeof ApiIptvCatalogScrapeRoute
  '/api/iptv-catalog-verify': typeof ApiIptvCatalogVerifyRoute
  '/api/iptv-share': typeof ApiIptvShareRoute
  '/api/iptv-paste-body': typeof ApiIptvPasteBodyRoute
  '/api/iptv-deep-ref-reprocess': typeof ApiIptvDeepRefReprocessRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_ops/': typeof OpsIndexRoute
  '/_auth/login/mfa': typeof AuthLoginMfaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/deep-refs'
    | '/pool'
    | '/providers'
    | '/scrape'
    | '/api/inngest'
    | '/api/iptv-catalog-scrape'
    | '/api/iptv-catalog-verify'
    | '/api/iptv-share'
    | '/api/iptv-paste-body'
    | '/api/iptv-deep-ref-reprocess'
    | '/auth/callback'
    | '/login/mfa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/deep-refs'
    | '/pool'
    | '/providers'
    | '/scrape'
    | '/api/inngest'
    | '/api/iptv-catalog-scrape'
    | '/api/iptv-catalog-verify'
    | '/api/iptv-share'
    | '/api/iptv-paste-body'
    | '/api/iptv-deep-ref-reprocess'
    | '/auth/callback'
    | '/login/mfa'
  id:
    | '__root__'
    | '/_auth'
    | '/_ops'
    | '/_auth/login'
    | '/_ops/accounts'
    | '/_ops/deep-refs'
    | '/_ops/pool'
    | '/_ops/providers'
    | '/_ops/scrape'
    | '/api/inngest'
    | '/api/iptv-catalog-scrape'
    | '/api/iptv-catalog-verify'
    | '/api/iptv-share'
    | '/api/iptv-paste-body'
    | '/api/iptv-deep-ref-reprocess'
    | '/auth/callback'
    | '/_ops/'
    | '/_auth/login/mfa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiIptvCatalogScrapeRoute: typeof ApiIptvCatalogScrapeRoute
  ApiIptvCatalogVerifyRoute: typeof ApiIptvCatalogVerifyRoute
  ApiIptvShareRoute: typeof ApiIptvShareRoute
  ApiIptvPasteBodyRoute: typeof ApiIptvPasteBodyRoute
  ApiIptvDeepRefReprocessRoute: typeof ApiIptvDeepRefReprocessRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops': {
      id: '/_ops'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_ops/': {
      id: '/_ops/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/accounts': {
      id: '/_ops/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof OpsAccountsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/deep-refs': {
      id: '/_ops/deep-refs'
      path: '/deep-refs'
      fullPath: '/deep-refs'
      preLoaderRoute: typeof OpsDeepRefsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/pool': {
      id: '/_ops/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof OpsPoolRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/providers': {
      id: '/_ops/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof OpsProvidersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/scrape': {
      id: '/_ops/scrape'
      path: '/scrape'
      fullPath: '/scrape'
      preLoaderRoute: typeof OpsScrapeRouteImport
      parentRoute: typeof OpsRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-catalog-scrape': {
      id: '/api/iptv-catalog-scrape'
      path: '/api/iptv-catalog-scrape'
      fullPath: '/api/iptv-catalog-scrape'
      preLoaderRoute: typeof ApiIptvCatalogScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-catalog-verify': {
      id: '/api/iptv-catalog-verify'
      path: '/api/iptv-catalog-verify'
      fullPath: '/api/iptv-catalog-verify'
      preLoaderRoute: typeof ApiIptvCatalogVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-share': {
      id: '/api/iptv-share'
      path: '/api/iptv-share'
      fullPath: '/api/iptv-share'
      preLoaderRoute: typeof ApiIptvShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-paste-body': {
      id: '/api/iptv-paste-body'
      path: '/api/iptv-paste-body'
      fullPath: '/api/iptv-paste-body'
      preLoaderRoute: typeof ApiIptvPasteBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-deep-ref-reprocess': {
      id: '/api/iptv-deep-ref-reprocess'
      path: '/api/iptv-deep-ref-reprocess'
      fullPath: '/api/iptv-deep-ref-reprocess'
      preLoaderRoute: typeof ApiIptvDeepRefReprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/mfa': {
      id: '/_auth/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof AuthLoginMfaRouteImport
      parentRoute: typeof AuthLoginRoute
    }
  }
}

interface AuthLoginRouteChildren {
  AuthLoginMfaRoute: typeof AuthLoginMfaRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLoginMfaRoute: AuthLoginMfaRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OpsRouteChildren {
  OpsAccountsRoute: typeof OpsAccountsRoute
  OpsDeepRefsRoute: typeof OpsDeepRefsRoute
  OpsPoolRoute: typeof OpsPoolRoute
  OpsProvidersRoute: typeof OpsProvidersRoute
  OpsScrapeRoute: typeof OpsScrapeRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAccountsRoute: OpsAccountsRoute,
  OpsDeepRefsRoute: OpsDeepRefsRoute,
  OpsPoolRoute: OpsPoolRoute,
  OpsProvidersRoute: OpsProvidersRoute,
  OpsScrapeRoute: OpsScrapeRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiIptvCatalogScrapeRoute: ApiIptvCatalogScrapeRoute,
  ApiIptvCatalogVerifyRoute: ApiIptvCatalogVerifyRoute,
  ApiIptvShareRoute: ApiIptvShareRoute,
  ApiIptvPasteBodyRoute: ApiIptvPasteBodyRoute,
  ApiIptvDeepRefReprocessRoute: ApiIptvDeepRefReprocessRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
