import 'dart:async';
import 'dart:isolate';

import 'package:flutter/foundation.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt_explode;

/// One closed-caption track as a direct WebVTT URL.
class YoutubeCaptionTrack {
  final String url;
  final String langCode;
  final String langName;
  final bool isAutoGenerated;

  const YoutubeCaptionTrack({
    required this.url,
    required this.langCode,
    required this.langName,
    this.isAutoGenerated = false,
  });
}

/// One selectable video-only quality. Shares [YoutubeResolvedStreams.audioUrl].
class YoutubeQuality {
  final int height;
  final String videoUrl;

  const YoutubeQuality({required this.height, required this.videoUrl});

  String get label => '${height}p';
}

/// Resolved playable URLs for a single YouTube video.
class YoutubeResolvedStreams {
  /// Default open URL. Prefer muxed progressive (A+V) for a fast audible start;
  /// adaptive video-only lives in [qualities] for the Quality menu.
  final String? playUrl;

  /// Resolution height of [playUrl] (muxed or adaptive pick).
  final int? playHeight;

  /// Separate AAC for video-only URLs in [qualities].
  /// Null when there is no adaptive ladder.
  final String? audioUrl;

  /// Muxed progressive (A+V) URL — typically ≤360p. Same as [playUrl] when
  /// muxed is the default open. Null when YouTube offered no muxed stream.
  final String? muxedUrl;

  final int? muxedHeight;

  final String? title;
  final String? thumbnailUrl;
  final int? durationSeconds;

  /// Video-only qualities (highest first). H.264 ≤1080p + VP9 above; no AV1.
  final List<YoutubeQuality> qualities;

  /// WebVTT caption tracks (empty when none / not fetched yet).
  final List<YoutubeCaptionTrack> captions;

  const YoutubeResolvedStreams({
    this.playUrl,
    this.playHeight,
    this.audioUrl,
    this.muxedUrl,
    this.muxedHeight,
    this.title,
    this.thumbnailUrl,
    this.durationSeconds,
    this.qualities = const [],
    this.captions = const [],
  });

  bool get hasPlayable => playUrl != null && playUrl!.isNotEmpty;

  YoutubeResolvedStreams copyWith({
    String? playUrl,
    int? playHeight,
    String? audioUrl,
    String? muxedUrl,
    int? muxedHeight,
    String? title,
    String? thumbnailUrl,
    int? durationSeconds,
    List<YoutubeQuality>? qualities,
    List<YoutubeCaptionTrack>? captions,
  }) {
    return YoutubeResolvedStreams(
      playUrl: playUrl ?? this.playUrl,
      playHeight: playHeight ?? this.playHeight,
      audioUrl: audioUrl ?? this.audioUrl,
      muxedUrl: muxedUrl ?? this.muxedUrl,
      muxedHeight: muxedHeight ?? this.muxedHeight,
      title: title ?? this.title,
      thumbnailUrl: thumbnailUrl ?? this.thumbnailUrl,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      qualities: qualities ?? this.qualities,
      captions: captions ?? this.captions,
    );
  }
}

class _ResolvedCacheEntry {
  final YoutubeResolvedStreams streams;
  final DateTime at;
  const _ResolvedCacheEntry(this.streams, this.at);
}

/// Resolve YouTube video ids to googlevideo URLs (Debrify path).
///
/// No search / InnerTube — stream extraction only via youtube_explode.
class YoutubeStreamService {
  YoutubeStreamService._();

  static const int defaultMaxHeight = 1080;
  static const Duration _resolveCacheTtl = Duration(minutes: 10);

  static final Map<String, _ResolvedCacheEntry> _resolveCache = {};
  static final Map<String, Future<YoutubeResolvedStreams?>> _resolveInFlight =
      {};
  static final Map<String, Future<List<YoutubeCaptionTrack>>> _captionsInFlight =
      {};

  /// Warm the resolve cache for upcoming trailer opens (no captions / metadata).
  static void prefetch(Iterable<String> videoIds, {int limit = 3}) {
    var n = 0;
    for (final id in videoIds) {
      if (id.isEmpty) continue;
      if (n >= limit) break;
      n++;
      unawaited(resolveStreams(id));
    }
  }

  /// Resolve [videoId] into playable URLs.
  ///
  /// Prefer ANDROID_VR client (mpv-friendly googlevideo URLs). Cap default
  /// adaptive ladder at [maxHeightOverride] or [defaultMaxHeight]. Default
  /// [playUrl] is muxed when available (fast audible open). Captions / metadata
  /// are opt-in so the trailer critical path stays lean.
  ///
  /// Pass [forceRefresh] on open / Quality switch — googlevideo URLs expire and
  /// the resolve cache must not reuse a poisoned/HEADed ladder.
  static Future<YoutubeResolvedStreams?> resolveStreams(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
    bool withMetadata = false,
    bool forceRefresh = false,
  }) {
    final key = _resolveKey(
      videoId,
      maxHeightOverride,
      withCaptions: withCaptions,
      withMetadata: withMetadata,
    );
    if (forceRefresh) {
      _resolveCache.remove(key);
      // Drop any in-flight resolve for this key so we do not await a stale one.
      _resolveInFlight.remove(key);
    } else {
      final cached = _resolveCache[key];
      if (cached != null &&
          DateTime.now().difference(cached.at) < _resolveCacheTtl) {
        return Future.value(cached.streams);
      }
      final inFlight = _resolveInFlight[key];
      if (inFlight != null) return inFlight;
    }
    final future = _resolveUncached(
      videoId,
      maxHeightOverride: maxHeightOverride,
      withCaptions: withCaptions,
      withMetadata: withMetadata,
    );
    _resolveInFlight[key] = future;
    return future.whenComplete(() => _resolveInFlight.remove(key));
  }

  /// Fetch WebVTT captions only (trailer CC menu). Does not re-extract streams.
  static Future<List<YoutubeCaptionTrack>> fetchCaptions(String videoId) {
    final inFlight = _captionsInFlight[videoId];
    if (inFlight != null) return inFlight;
    final future = _fetchCaptionsUncached(videoId);
    _captionsInFlight[videoId] = future;
    return future.whenComplete(() => _captionsInFlight.remove(videoId));
  }

  static String _resolveKey(
    String videoId,
    int? maxHeightOverride, {
    required bool withCaptions,
    required bool withMetadata,
  }) {
    final base = maxHeightOverride == null
        ? videoId
        : '$videoId#h$maxHeightOverride';
    final cc = withCaptions ? '#cc' : '';
    final meta = withMetadata ? '#meta' : '';
    return '$base$cc$meta';
  }

  static Future<YoutubeResolvedStreams?> _resolveUncached(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
    bool withMetadata = false,
  }) async {
    final maxHeight = maxHeightOverride ?? defaultMaxHeight;
    try {
      final streams = await Isolate.run(
        () => _resolveStreamsBlocking(
          videoId,
          maxHeight,
          withCaptions,
          withMetadata,
        ),
      );
      if (streams != null) {
        _resolveCache.removeWhere(
          (_, e) => DateTime.now().difference(e.at) >= _resolveCacheTtl,
        );
        _resolveCache[_resolveKey(
          videoId,
          maxHeightOverride,
          withCaptions: withCaptions,
          withMetadata: withMetadata,
        )] = _ResolvedCacheEntry(streams, DateTime.now());
      }
      return streams;
    } catch (e) {
      debugPrint('YoutubeStreamService: resolve failed for $videoId — $e');
      return null;
    }
  }

  static Future<List<YoutubeCaptionTrack>> _fetchCaptionsUncached(
    String videoId,
  ) async {
    try {
      return await Isolate.run(() => _fetchCaptionsBlocking(videoId));
    } catch (e) {
      debugPrint('YoutubeStreamService: captions failed for $videoId — $e');
      return const [];
    }
  }

  static Future<List<YoutubeCaptionTrack>> _fetchCaptionsBlocking(
    String videoId,
  ) async {
    final yt = yt_explode.YoutubeExplode();
    try {
      final ccManifest = await yt.videos.closedCaptions.getManifest(
        videoId,
        formats: const [yt_explode.ClosedCaptionFormat.vtt],
      );
      return [
        for (final t in ccManifest.tracks)
          YoutubeCaptionTrack(
            url: t.url.toString(),
            langCode: t.language.code,
            langName: t.language.name.isNotEmpty
                ? t.language.name
                : t.language.code,
            isAutoGenerated: t.isAutoGenerated,
          ),
      ];
    } finally {
      try {
        yt.close();
      } catch (_) {}
    }
  }

  static Future<YoutubeResolvedStreams?> _resolveStreamsBlocking(
    String videoId,
    int maxHeight,
    bool withCaptions,
    bool withMetadata,
  ) async {
    final yt = yt_explode.YoutubeExplode();
    try {
      // ONE client per attempt — never pass multiple ytClients in one call.
      // youtube_explode merges every client's streams; mixing androidVr video
      // with tv/ios audio yields googlevideo URLs that open as playing=true
      // with dur=0 / no frames (Quality stuck on muxed 360p).
      yt_explode.StreamManifest? manifest;
      final clientAttempts = <List<yt_explode.YoutubeApiClient>?>[
        [yt_explode.YoutubeApiClient.androidVr],
        [yt_explode.YoutubeApiClient.tv],
        [yt_explode.YoutubeApiClient.androidSdkless],
        [yt_explode.YoutubeApiClient.ios],
        null, // library default
      ];
      Object? lastError;
      for (final clients in clientAttempts) {
        try {
          final m = clients == null
              ? await yt.videos.streamsClient.getManifest(videoId)
              : await yt.videos.streamsClient.getManifest(
                  videoId,
                  ytClients: clients,
                );
          if (m.muxed.isNotEmpty || m.videoOnly.isNotEmpty) {
            manifest = m;
            break;
          }
        } catch (e) {
          lastError = e;
        }
      }
      if (manifest == null) {
        throw lastError ??
            StateError('No YouTube streams for $videoId');
      }

      final muxed = manifest.muxed.toList()
        ..sort(
          (a, b) =>
              b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
        );
      final muxedMp4 =
          muxed.where((s) => s.container.name.toLowerCase() == 'mp4');
      final bestMuxedStream =
          muxedMp4.isNotEmpty ? muxedMp4.first : (muxed.isNotEmpty ? muxed.first : null);
      final bestMuxed = bestMuxedStream?.url.toString();
      final bestMuxedHeight = bestMuxedStream?.videoResolution.height;

      bool isAvc(String c) => c.toLowerCase().contains('avc');
      bool isVp9(String c) {
        final l = c.toLowerCase();
        return l.contains('vp9') || l.contains('vp09');
      }

      String? playUrl;
      int? playHeight;
      String? audioUrl;
      final qualities = <YoutubeQuality>[];
      final videoOnly = manifest.videoOnly
          .where((s) => isAvc(s.videoCodec) || isVp9(s.videoCodec))
          .toList();
      final audioStreams = manifest.audioOnly
          .where((s) => s.container.name.toLowerCase() == 'mp4')
          .toList();
      if (videoOnly.isNotEmpty && audioStreams.isNotEmpty) {
        videoOnly.sort((a, b) {
          final byHeight =
              b.videoResolution.height.compareTo(a.videoResolution.height);
          if (byHeight != 0) return byHeight;
          final aAvc = isAvc(a.videoCodec);
          final bAvc = isAvc(b.videoCodec);
          if (aAvc == bAvc) return 0;
          return aAvc ? -1 : 1;
        });

        final seenHeights = <int>{};
        for (final s in videoOnly) {
          final h = s.videoResolution.height;
          if (!seenHeights.add(h)) continue;
          qualities.add(YoutubeQuality(height: h, videoUrl: s.url.toString()));
        }

        audioStreams.sort(
          (a, b) =>
              b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
        );
        audioUrl = audioStreams.first.url.toString();
      }

      // Muxed first (Debrify launch): instant A+V. Adaptive ladder stays in
      // [qualities] for HD Quality switches — desktop adaptive attach often
      // stalls (playing=true, dur=0, no frame).
      if (bestMuxed != null) {
        playUrl = bestMuxed;
        playHeight = bestMuxedHeight;
      } else if (qualities.isNotEmpty) {
        final atOrBelow =
            qualities.where((q) => q.height <= maxHeight).toList();
        final pick =
            atOrBelow.isNotEmpty ? atOrBelow.first : qualities.last;
        playUrl = pick.videoUrl;
        playHeight = pick.height;
      }
      if (playUrl == null) return null;

      String? title;
      String? thumb;
      int? duration;
      final captions = <YoutubeCaptionTrack>[];
      if (withMetadata || withCaptions) {
        await Future.wait([
          () async {
            if (!withMetadata) return;
            try {
              final video = await yt.videos.get(videoId);
              title = video.title;
              thumb = video.thumbnails.highResUrl;
              duration = video.duration?.inSeconds;
            } catch (_) {}
          }(),
          () async {
            if (!withCaptions) return;
            try {
              final ccManifest = await yt.videos.closedCaptions.getManifest(
                videoId,
                formats: const [yt_explode.ClosedCaptionFormat.vtt],
              );
              for (final t in ccManifest.tracks) {
                captions.add(
                  YoutubeCaptionTrack(
                    url: t.url.toString(),
                    langCode: t.language.code,
                    langName: t.language.name.isNotEmpty
                        ? t.language.name
                        : t.language.code,
                    isAutoGenerated: t.isAutoGenerated,
                  ),
                );
              }
            } catch (_) {}
          }(),
        ]);
      }

      return YoutubeResolvedStreams(
        playUrl: playUrl,
        playHeight: playHeight,
        audioUrl: audioUrl,
        muxedUrl: bestMuxed,
        muxedHeight: bestMuxedHeight,
        title: title,
        thumbnailUrl: thumb,
        durationSeconds: duration,
        qualities: qualities,
        captions: captions,
      );
    } finally {
      try {
        yt.close();
      } catch (_) {}
    }
  }
}
