-- Local seed after `supabase db reset`.
-- Auth users cannot be inserted from SQL (Admin Auth API only).
-- `node scripts/create-forja-test-users.js` (or `reset-forja-supabase.js`) creates:
--   - auth users + public.accounts (user@forja.local is is_admin)
--   - profiles + lean profile_settings
--   - global iptv_portals
--
-- Test logins:
--   user@forja.local / password123  (admin → /admin)
--   demo@forja.local / password123
