name: forja_design
description: Design system and shared widgets for Forja
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
