/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as IptvRouteImport } from './routes/iptv'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiLatestReleaseRouteImport } from './routes/api.latest-release'
import { Route as ApiChangelogRouteImport } from './routes/api.changelog'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountProfilesRouteImport } from './routes/account.profiles'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthConnectRouteImport } from './routes/_auth/connect'
import { Route as AccountSettingsStremioRouteImport } from './routes/account.settings.stremio'
import { Route as AccountSettingsProvidersRouteImport } from './routes/account.settings.providers'
import { Route as AccountSettingsPlaybackRouteImport } from './routes/account.settings.playback'
import { Route as AccountSettingsNuvioRouteImport } from './routes/account.settings.nuvio'
import { Route as AccountSettingsNavigationRouteImport } from './routes/account.settings.navigation'
import { Route as AccountSettingsIptvRouteImport } from './routes/account.settings.iptv'
import { Route as AccountSettingsConnectionsRouteImport } from './routes/account.settings.connections'
import { Route as AccountSettingsAccountRouteImport } from './routes/account.settings.account'
import { Route as AuthLoginMfaRouteImport } from './routes/_auth/login.mfa'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvRoute = IptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLatestReleaseRoute = ApiLatestReleaseRouteImport.update({
  id: '/api/latest-release',
  path: '/api/latest-release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogRoute = ApiChangelogRouteImport.update({
  id: '/api/changelog',
  path: '/api/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfilesRoute = AccountProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AccountRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConnectRoute = AuthConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthRoute,
} as any)
const AccountSettingsStremioRoute = AccountSettingsStremioRouteImport.update({
  id: '/stremio',
  path: '/stremio',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsProvidersRoute =
  AccountSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsPlaybackRoute = AccountSettingsPlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsNuvioRoute = AccountSettingsNuvioRouteImport.update({
  id: '/nuvio',
  path: '/nuvio',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsNavigationRoute =
  AccountSettingsNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsIptvRoute = AccountSettingsIptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsConnectionsRoute =
  AccountSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsAccountRoute = AccountSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AuthLoginMfaRoute = AuthLoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/iptv': typeof IptvRoute
  '/terms': typeof TermsRoute
  '/connect': typeof AuthConnectRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/account/profiles': typeof AccountProfilesRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/api/changelog': typeof ApiChangelogRoute
  '/api/latest-release': typeof ApiLatestReleaseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/mfa': typeof AuthLoginMfaRoute
  '/account/settings/account': typeof AccountSettingsAccountRoute
  '/account/settings/connections': typeof AccountSettingsConnectionsRoute
  '/account/settings/iptv': typeof AccountSettingsIptvRoute
  '/account/settings/navigation': typeof AccountSettingsNavigationRoute
  '/account/settings/nuvio': typeof AccountSettingsNuvioRoute
  '/account/settings/playback': typeof AccountSettingsPlaybackRoute
  '/account/settings/providers': typeof AccountSettingsProvidersRoute
  '/account/settings/stremio': typeof AccountSettingsStremioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/iptv': typeof IptvRoute
  '/terms': typeof TermsRoute
  '/connect': typeof AuthConnectRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRouteWithChildren
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/account/profiles': typeof AccountProfilesRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/api/changelog': typeof ApiChangelogRoute
  '/api/latest-release': typeof ApiLatestReleaseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/login/mfa': typeof AuthLoginMfaRoute
  '/account/settings/account': typeof AccountSettingsAccountRoute
  '/account/settings/connections': typeof AccountSettingsConnectionsRoute
  '/account/settings/iptv': typeof AccountSettingsIptvRoute
  '/account/settings/navigation': typeof AccountSettingsNavigationRoute
  '/account/settings/nuvio': typeof AccountSettingsNuvioRoute
  '/account/settings/playback': typeof AccountSettingsPlaybackRoute
  '/account/settings/providers': typeof AccountSettingsProvidersRoute
  '/account/settings/stremio': typeof AccountSettingsStremioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/iptv': typeof IptvRoute
  '/terms': typeof TermsRoute
  '/_auth/connect': typeof AuthConnectRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRouteWithChildren
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/account/profiles': typeof AccountProfilesRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/api/changelog': typeof ApiChangelogRoute
  '/api/latest-release': typeof ApiLatestReleaseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/login/mfa': typeof AuthLoginMfaRoute
  '/account/settings/account': typeof AccountSettingsAccountRoute
  '/account/settings/connections': typeof AccountSettingsConnectionsRoute
  '/account/settings/iptv': typeof AccountSettingsIptvRoute
  '/account/settings/navigation': typeof AccountSettingsNavigationRoute
  '/account/settings/nuvio': typeof AccountSettingsNuvioRoute
  '/account/settings/playback': typeof AccountSettingsPlaybackRoute
  '/account/settings/providers': typeof AccountSettingsProvidersRoute
  '/account/settings/stremio': typeof AccountSettingsStremioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/changelog'
    | '/dmca'
    | '/download'
    | '/iptv'
    | '/terms'
    | '/connect'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account/profiles'
    | '/account/settings'
    | '/api/changelog'
    | '/api/latest-release'
    | '/auth/callback'
    | '/login/mfa'
    | '/account/settings/account'
    | '/account/settings/connections'
    | '/account/settings/iptv'
    | '/account/settings/navigation'
    | '/account/settings/nuvio'
    | '/account/settings/playback'
    | '/account/settings/providers'
    | '/account/settings/stremio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/changelog'
    | '/dmca'
    | '/download'
    | '/iptv'
    | '/terms'
    | '/connect'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account/profiles'
    | '/account/settings'
    | '/api/changelog'
    | '/api/latest-release'
    | '/auth/callback'
    | '/login/mfa'
    | '/account/settings/account'
    | '/account/settings/connections'
    | '/account/settings/iptv'
    | '/account/settings/navigation'
    | '/account/settings/nuvio'
    | '/account/settings/playback'
    | '/account/settings/providers'
    | '/account/settings/stremio'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/account'
    | '/changelog'
    | '/dmca'
    | '/download'
    | '/iptv'
    | '/terms'
    | '/_auth/connect'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/account/profiles'
    | '/account/settings'
    | '/api/changelog'
    | '/api/latest-release'
    | '/auth/callback'
    | '/_auth/login/mfa'
    | '/account/settings/account'
    | '/account/settings/connections'
    | '/account/settings/iptv'
    | '/account/settings/navigation'
    | '/account/settings/nuvio'
    | '/account/settings/playback'
    | '/account/settings/providers'
    | '/account/settings/stremio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DmcaRoute: typeof DmcaRoute
  DownloadRoute: typeof DownloadRoute
  IptvRoute: typeof IptvRoute
  TermsRoute: typeof TermsRoute
  ApiChangelogRoute: typeof ApiChangelogRoute
  ApiLatestReleaseRoute: typeof ApiLatestReleaseRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv': {
      id: '/iptv'
      path: '/iptv'
      fullPath: '/iptv'
      preLoaderRoute: typeof IptvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/latest-release': {
      id: '/api/latest-release'
      path: '/api/latest-release'
      fullPath: '/api/latest-release'
      preLoaderRoute: typeof ApiLatestReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog': {
      id: '/api/changelog'
      path: '/api/changelog'
      fullPath: '/api/changelog'
      preLoaderRoute: typeof ApiChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profiles': {
      id: '/account/profiles'
      path: '/profiles'
      fullPath: '/account/profiles'
      preLoaderRoute: typeof AccountProfilesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/connect': {
      id: '/_auth/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthConnectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/account/settings/stremio': {
      id: '/account/settings/stremio'
      path: '/stremio'
      fullPath: '/account/settings/stremio'
      preLoaderRoute: typeof AccountSettingsStremioRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/providers': {
      id: '/account/settings/providers'
      path: '/providers'
      fullPath: '/account/settings/providers'
      preLoaderRoute: typeof AccountSettingsProvidersRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/playback': {
      id: '/account/settings/playback'
      path: '/playback'
      fullPath: '/account/settings/playback'
      preLoaderRoute: typeof AccountSettingsPlaybackRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/nuvio': {
      id: '/account/settings/nuvio'
      path: '/nuvio'
      fullPath: '/account/settings/nuvio'
      preLoaderRoute: typeof AccountSettingsNuvioRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/navigation': {
      id: '/account/settings/navigation'
      path: '/navigation'
      fullPath: '/account/settings/navigation'
      preLoaderRoute: typeof AccountSettingsNavigationRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/iptv': {
      id: '/account/settings/iptv'
      path: '/iptv'
      fullPath: '/account/settings/iptv'
      preLoaderRoute: typeof AccountSettingsIptvRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/connections': {
      id: '/account/settings/connections'
      path: '/connections'
      fullPath: '/account/settings/connections'
      preLoaderRoute: typeof AccountSettingsConnectionsRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/account': {
      id: '/account/settings/account'
      path: '/account'
      fullPath: '/account/settings/account'
      preLoaderRoute: typeof AccountSettingsAccountRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/_auth/login/mfa': {
      id: '/_auth/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof AuthLoginMfaRouteImport
      parentRoute: typeof AuthLoginRoute
    }
  }
}

interface AuthLoginRouteChildren {
  AuthLoginMfaRoute: typeof AuthLoginMfaRoute
}

const AuthLoginRouteChildren: AuthLoginRouteChildren = {
  AuthLoginMfaRoute: AuthLoginMfaRoute,
}

const AuthLoginRouteWithChildren = AuthLoginRoute._addFileChildren(
  AuthLoginRouteChildren,
)

interface AuthRouteChildren {
  AuthConnectRoute: typeof AuthConnectRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRouteWithChildren
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConnectRoute: AuthConnectRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRouteWithChildren,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AccountSettingsRouteChildren {
  AccountSettingsAccountRoute: typeof AccountSettingsAccountRoute
  AccountSettingsConnectionsRoute: typeof AccountSettingsConnectionsRoute
  AccountSettingsIptvRoute: typeof AccountSettingsIptvRoute
  AccountSettingsNavigationRoute: typeof AccountSettingsNavigationRoute
  AccountSettingsNuvioRoute: typeof AccountSettingsNuvioRoute
  AccountSettingsPlaybackRoute: typeof AccountSettingsPlaybackRoute
  AccountSettingsProvidersRoute: typeof AccountSettingsProvidersRoute
  AccountSettingsStremioRoute: typeof AccountSettingsStremioRoute
}

const AccountSettingsRouteChildren: AccountSettingsRouteChildren = {
  AccountSettingsAccountRoute: AccountSettingsAccountRoute,
  AccountSettingsConnectionsRoute: AccountSettingsConnectionsRoute,
  AccountSettingsIptvRoute: AccountSettingsIptvRoute,
  AccountSettingsNavigationRoute: AccountSettingsNavigationRoute,
  AccountSettingsNuvioRoute: AccountSettingsNuvioRoute,
  AccountSettingsPlaybackRoute: AccountSettingsPlaybackRoute,
  AccountSettingsProvidersRoute: AccountSettingsProvidersRoute,
  AccountSettingsStremioRoute: AccountSettingsStremioRoute,
}

const AccountSettingsRouteWithChildren = AccountSettingsRoute._addFileChildren(
  AccountSettingsRouteChildren,
)

interface AccountRouteChildren {
  AccountProfilesRoute: typeof AccountProfilesRoute
  AccountSettingsRoute: typeof AccountSettingsRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfilesRoute: AccountProfilesRoute,
  AccountSettingsRoute: AccountSettingsRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DmcaRoute: DmcaRoute,
  DownloadRoute: DownloadRoute,
  IptvRoute: IptvRoute,
  TermsRoute: TermsRoute,
  ApiChangelogRoute: ApiChangelogRoute,
  ApiLatestReleaseRoute: ApiLatestReleaseRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
