/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IptvRouteImport } from './routes/iptv'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIptvShareRouteImport } from './routes/api.iptv-share'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountProfilesRouteImport } from './routes/account.profiles'
import { Route as AccountSettingsStremioRouteImport } from './routes/account.settings.stremio'
import { Route as AccountSettingsProvidersRouteImport } from './routes/account.settings.providers'
import { Route as AccountSettingsPlaybackRouteImport } from './routes/account.settings.playback'
import { Route as AccountSettingsNavigationRouteImport } from './routes/account.settings.navigation'
import { Route as AccountSettingsIptvRouteImport } from './routes/account.settings.iptv'
import { Route as AccountSettingsAccountRouteImport } from './routes/account.settings.account'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvRoute = IptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIptvShareRoute = ApiIptvShareRouteImport.update({
  id: '/api/iptv-share',
  path: '/api/iptv-share',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfilesRoute = AccountProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsStremioRoute = AccountSettingsStremioRouteImport.update({
  id: '/stremio',
  path: '/stremio',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsProvidersRoute =
  AccountSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsPlaybackRoute = AccountSettingsPlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsNavigationRoute =
  AccountSettingsNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsIptvRoute = AccountSettingsIptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => AccountSettingsRoute,
} as any)
const AccountSettingsAccountRoute = AccountSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AccountSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/iptv': typeof IptvRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/profiles': typeof AccountProfilesRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/api/iptv-share': typeof ApiIptvShareRoute
  '/account/settings/account': typeof AccountSettingsAccountRoute
  '/account/settings/iptv': typeof AccountSettingsIptvRoute
  '/account/settings/navigation': typeof AccountSettingsNavigationRoute
  '/account/settings/playback': typeof AccountSettingsPlaybackRoute
  '/account/settings/providers': typeof AccountSettingsProvidersRoute
  '/account/settings/stremio': typeof AccountSettingsStremioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/iptv': typeof IptvRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/profiles': typeof AccountProfilesRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/api/iptv-share': typeof ApiIptvShareRoute
  '/account/settings/account': typeof AccountSettingsAccountRoute
  '/account/settings/iptv': typeof AccountSettingsIptvRoute
  '/account/settings/navigation': typeof AccountSettingsNavigationRoute
  '/account/settings/playback': typeof AccountSettingsPlaybackRoute
  '/account/settings/providers': typeof AccountSettingsProvidersRoute
  '/account/settings/stremio': typeof AccountSettingsStremioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/iptv': typeof IptvRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/profiles': typeof AccountProfilesRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/api/iptv-share': typeof ApiIptvShareRoute
  '/account/settings/account': typeof AccountSettingsAccountRoute
  '/account/settings/iptv': typeof AccountSettingsIptvRoute
  '/account/settings/navigation': typeof AccountSettingsNavigationRoute
  '/account/settings/playback': typeof AccountSettingsPlaybackRoute
  '/account/settings/providers': typeof AccountSettingsProvidersRoute
  '/account/settings/stremio': typeof AccountSettingsStremioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/changelog'
    | '/dmca'
    | '/download'
    | '/forgot-password'
    | '/iptv'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/account/profiles'
    | '/account/settings'
    | '/api/iptv-share'
    | '/account/settings/account'
    | '/account/settings/iptv'
    | '/account/settings/navigation'
    | '/account/settings/playback'
    | '/account/settings/providers'
    | '/account/settings/stremio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/changelog'
    | '/dmca'
    | '/download'
    | '/forgot-password'
    | '/iptv'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/account/profiles'
    | '/account/settings'
    | '/api/iptv-share'
    | '/account/settings/account'
    | '/account/settings/iptv'
    | '/account/settings/navigation'
    | '/account/settings/playback'
    | '/account/settings/providers'
    | '/account/settings/stremio'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/changelog'
    | '/dmca'
    | '/download'
    | '/forgot-password'
    | '/iptv'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/account/profiles'
    | '/account/settings'
    | '/api/iptv-share'
    | '/account/settings/account'
    | '/account/settings/iptv'
    | '/account/settings/navigation'
    | '/account/settings/playback'
    | '/account/settings/providers'
    | '/account/settings/stremio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DmcaRoute: typeof DmcaRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IptvRoute: typeof IptvRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiIptvShareRoute: typeof ApiIptvShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv': {
      id: '/iptv'
      path: '/iptv'
      fullPath: '/iptv'
      preLoaderRoute: typeof IptvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iptv-share': {
      id: '/api/iptv-share'
      path: '/api/iptv-share'
      fullPath: '/api/iptv-share'
      preLoaderRoute: typeof ApiIptvShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profiles': {
      id: '/account/profiles'
      path: '/profiles'
      fullPath: '/account/profiles'
      preLoaderRoute: typeof AccountProfilesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings/stremio': {
      id: '/account/settings/stremio'
      path: '/stremio'
      fullPath: '/account/settings/stremio'
      preLoaderRoute: typeof AccountSettingsStremioRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/providers': {
      id: '/account/settings/providers'
      path: '/providers'
      fullPath: '/account/settings/providers'
      preLoaderRoute: typeof AccountSettingsProvidersRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/playback': {
      id: '/account/settings/playback'
      path: '/playback'
      fullPath: '/account/settings/playback'
      preLoaderRoute: typeof AccountSettingsPlaybackRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/navigation': {
      id: '/account/settings/navigation'
      path: '/navigation'
      fullPath: '/account/settings/navigation'
      preLoaderRoute: typeof AccountSettingsNavigationRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/iptv': {
      id: '/account/settings/iptv'
      path: '/iptv'
      fullPath: '/account/settings/iptv'
      preLoaderRoute: typeof AccountSettingsIptvRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/account': {
      id: '/account/settings/account'
      path: '/account'
      fullPath: '/account/settings/account'
      preLoaderRoute: typeof AccountSettingsAccountRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
  }
}

interface AccountSettingsRouteChildren {
  AccountSettingsAccountRoute: typeof AccountSettingsAccountRoute
  AccountSettingsIptvRoute: typeof AccountSettingsIptvRoute
  AccountSettingsNavigationRoute: typeof AccountSettingsNavigationRoute
  AccountSettingsPlaybackRoute: typeof AccountSettingsPlaybackRoute
  AccountSettingsProvidersRoute: typeof AccountSettingsProvidersRoute
  AccountSettingsStremioRoute: typeof AccountSettingsStremioRoute
}

const AccountSettingsRouteChildren: AccountSettingsRouteChildren = {
  AccountSettingsAccountRoute: AccountSettingsAccountRoute,
  AccountSettingsIptvRoute: AccountSettingsIptvRoute,
  AccountSettingsNavigationRoute: AccountSettingsNavigationRoute,
  AccountSettingsPlaybackRoute: AccountSettingsPlaybackRoute,
  AccountSettingsProvidersRoute: AccountSettingsProvidersRoute,
  AccountSettingsStremioRoute: AccountSettingsStremioRoute,
}

const AccountSettingsRouteWithChildren = AccountSettingsRoute._addFileChildren(
  AccountSettingsRouteChildren,
)

interface AccountRouteChildren {
  AccountProfilesRoute: typeof AccountProfilesRoute
  AccountSettingsRoute: typeof AccountSettingsRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfilesRoute: AccountProfilesRoute,
  AccountSettingsRoute: AccountSettingsRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DmcaRoute: DmcaRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IptvRoute: IptvRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiIptvShareRoute: ApiIptvShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
