/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IptvRouteImport } from './routes/iptv'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvRoute = IptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/iptv': typeof IptvRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/settings': typeof AccountSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/iptv': typeof IptvRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/settings': typeof AccountSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/dmca': typeof DmcaRoute
  '/download': typeof DownloadRoute
  '/iptv': typeof IptvRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/settings': typeof AccountSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dmca'
    | '/download'
    | '/iptv'
    | '/login'
    | '/signup'
    | '/terms'
    | '/account/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dmca'
    | '/download'
    | '/iptv'
    | '/login'
    | '/signup'
    | '/terms'
    | '/account/settings'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dmca'
    | '/download'
    | '/iptv'
    | '/login'
    | '/signup'
    | '/terms'
    | '/account/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  DmcaRoute: typeof DmcaRoute
  DownloadRoute: typeof DownloadRoute
  IptvRoute: typeof IptvRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv': {
      id: '/iptv'
      path: '/iptv'
      fullPath: '/iptv'
      preLoaderRoute: typeof IptvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountSettingsRoute: typeof AccountSettingsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountSettingsRoute: AccountSettingsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  DmcaRoute: DmcaRoute,
  DownloadRoute: DownloadRoute,
  IptvRoute: IptvRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
