// kisskh.co backend — Asian Drama (KDrama / CDrama / JDrama / Anime / Hollywood).
//
// Catalog/metadata API runs in Rust (`kisskh-core`). Stream extraction is gated
// by a signed `kkey` parameter generated by the site's own JS; that part stays
// in `KissKhExtractor` (headless webview).

import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'package:rust/rust.dart';

class KissKhService {
  static const String baseUrl = 'https://kisskh.co';
  static const String apiBase = '$baseUrl/api';

  // ─── Public API (Rust engine) ─────────────────────────────────
  Future<KdramaHomeFeed> getHome() async {
    final decoded = await kisskhCatalog({'action': 'home'});
    return KdramaHomeFeed.fromEngineJson(decoded);
  }

  Future<List<KdramaCard>> search(String query) async {
    final decoded = await kisskhCatalog({
      'action': 'search',
      'query': query,
    });
    return _parseCards(decoded['cards']);
  }

  /// Browse the global catalog with filters. Backs the Explore screen.
  ///
  /// Filter codes (kisskh.ovh / kisskh.co Angular SPA):
  ///   type:    0=All, 1=TVSeries, 2=Movie, 3=Anime, 4=Hollywood
  ///   sub:     0=All, 1=English, 2=Khmer, 3=Indonesian, 4=Malay,
  ///            5=Thai, 6=Arabic
  ///   country: 0=All, 1=South Korea, 2=Chinese, 3=United States,
  ///            4=Thailand, 5=Philippine, 6=Japanese, 7=Hong Kong, 8=Taiwan
  ///   status:  0=All, 1=Ongoing, 2=Completed, 3=Upcoming
  ///   order:   1=Popular, 2=Last Update, 3=Release Date
  Future<KdramaExplorePage> explore({
    int page = 1,
    int type = 0,
    int sub = 0,
    int country = 0,
    int status = 0,
    int order = 1,
    int pageSize = 40,
  }) async {
    try {
      final decoded = await kisskhCatalog({
        'action': 'explore',
        'page': page,
        'type_filter': type,
        'sub': sub,
        'country': country,
        'status': status,
        'order': order,
        'page_size': pageSize,
      });
      return KdramaExplorePage.fromEngineJson(decoded);
    } catch (e) {
      debugPrint('[KissKh] explore failed: $e');
      return const KdramaExplorePage(items: [], total: 0, page: 1);
    }
  }

  Future<KdramaDetails> getDetails(int id) async {
    final decoded = await kisskhCatalog({
      'action': 'details',
      'id': id,
    });
    return KdramaDetails.fromEngineJson(decoded);
  }

  /// List endpoints omit year/type — fill from `/Drama/{id}` (cached in Rust).
  Future<List<KdramaCard>> enrichCards(List<KdramaCard> cards) async {
    if (cards.isEmpty) return cards;
    final decoded = await kisskhCatalog({
      'action': 'enrich_cards',
      'cards_json': jsonEncode(cards.map((c) => c.toEngineJson()).toList()),
    });
    return _parseCards(decoded['cards']);
  }

  Future<KdramaHomeFeed> enrichHomeFeed(KdramaHomeFeed feed) async {
    final decoded = await kisskhCatalog({
      'action': 'enrich_home_feed',
      'feed_json': jsonEncode(feed.toEngineJson()),
    });
    return KdramaHomeFeed.fromEngineJson(decoded);
  }

  List<KdramaCard> _parseCards(dynamic raw) {
    final list = raw as List<dynamic>? ?? const [];
    return list
        .map((e) => KdramaCard.fromEngineJson(e as Map<String, dynamic>))
        .toList();
  }

  static String? yearFromRelease(String releaseDate) {
    if (releaseDate.length >= 4) {
      final y = releaseDate.substring(0, 4);
      if (RegExp(r'^\d{4}$').hasMatch(y)) return y;
    }
    return null;
  }

  /// Slug for URL building (title with spaces → dashes, lowercased).
  static String slugify(String title) {
    final s = title
        .toLowerCase()
        .replaceAll(RegExp(r"[''‘’`]"), '')
        .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
        .replaceAll(RegExp(r'-+'), '-')
        .replaceAll(RegExp(r'^-|-$'), '');
    return s.isEmpty ? 'drama' : s;
  }

  /// Episode page URL — used as the WebView entry-point for the extractor.
  static String episodePageUrl({
    required int dramaId,
    required String title,
    required int episodeId,
    required double episodeNumber,
  }) {
    final slug = slugify(title);
    final epLabel = episodeNumber == episodeNumber.truncateToDouble()
        ? episodeNumber.toInt().toString()
        : episodeNumber.toString();
    return '$baseUrl/Drama/$slug/Episode-$epLabel'
        '?id=$dramaId&ep=$episodeId&page=0&pageSize=100';
  }

  // ─── Watch history (continue watching) ──────────────────────────
  static const String _historyKey = 'kisskh_history_v1';

  static final ValueNotifier<int> watchHistoryRevision = ValueNotifier<int>(0);

  Future<void> recordWatch({
    required KdramaCard drama,
    required double episodeNumber,
    required int totalEpisodes,
    int? episodeId,
    List<KdramaEpisode> episodes = const [],
    Duration? position,
    Duration? duration,
  }) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(_historyKey) ?? [];
    list.removeWhere((e) {
      try {
        return jsonDecode(e)['id'] == drama.id;
      } catch (_) {
        return true;
      }
    });
    list.insert(
      0,
      jsonEncode({
        'id': drama.id,
        'title': drama.title,
        'cover': drama.cover,
        'episodeNumber': episodeNumber,
        if (episodeId != null && episodeId > 0) 'episodeId': episodeId,
        'totalEpisodes': totalEpisodes,
        if (episodes.isNotEmpty)
          'episodes': episodes
              .map(
                (e) => {
                  'id': e.id,
                  'number': e.number,
                  if (e.sub != 0) 'sub': e.sub,
                },
              )
              .toList(),
        'positionMs': position?.inMilliseconds ?? 0,
        'durationMs': duration?.inMilliseconds ?? 0,
        'updatedAt': DateTime.now().millisecondsSinceEpoch,
      }),
    );
    if (list.length > 50) list.removeRange(50, list.length);
    await p.setStringList(_historyKey, list);
    watchHistoryRevision.value++;
  }

  /// Reconstruct kisskh episode rows saved with [recordWatch].
  static List<KdramaEpisode> episodesFromHistory(Map<String, dynamic> entry) {
    final raw = entry['episodes'] as List?;
    if (raw == null || raw.isEmpty) return const [];
    final out = <KdramaEpisode>[];
    for (final item in raw) {
      if (item is! Map) continue;
      final id = (item['id'] as num?)?.toInt();
      final number = (item['number'] as num?)?.toDouble();
      if (id == null || number == null) continue;
      out.add(
        KdramaEpisode(
          id: id,
          number: number,
          sub: (item['sub'] as num?)?.toInt() ?? 0,
        ),
      );
    }
    out.sort((a, b) => a.number.compareTo(b.number));
    return out;
  }

  /// Same seek math as details → Resume.
  static Duration? startPositionFromHistory(Map<String, dynamic> entry) {
    final posMs = (entry['positionMs'] as num?)?.toInt() ?? 0;
    final durMs = (entry['durationMs'] as num?)?.toInt() ?? 0;
    if (posMs <= 5000) return null;
    final clamped =
        (durMs > 0 && posMs > durMs - 30000) ? (durMs - 30000) : posMs;
    return Duration(milliseconds: (clamped - 3000).clamp(0, 1 << 31));
  }

  /// Match watch-history entry to a live episode row (number first — stable
  /// across kisskh API id churn; id is a secondary hint).
  static KdramaEpisode? matchResumeEpisode({
    required List<KdramaEpisode> episodes,
    required double episodeNumber,
    int? episodeId,
  }) {
    if (episodes.isEmpty) return null;
    for (final e in episodes) {
      if (e.number == episodeNumber) return e;
    }
    if (episodeId != null && episodeId > 0) {
      try {
        return episodes.firstWhere((e) => e.id == episodeId);
      } catch (_) {}
    }
    return episodes.first;
  }

  Future<List<Map<String, dynamic>>> getWatchHistory() async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(_historyKey) ?? [];
    final out = <Map<String, dynamic>>[];
    for (final raw in list) {
      try {
        out.add(jsonDecode(raw) as Map<String, dynamic>);
      } catch (_) {}
    }
    return out;
  }

  Future<Map<String, dynamic>?> getProgress(int id) async {
    final all = await getWatchHistory();
    for (final h in all) {
      if ((h['id'] as num?)?.toInt() == id) return h;
    }
    return null;
  }

  Future<void> removeFromHistory(int id) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(_historyKey) ?? [];
    list.removeWhere((e) {
      try {
        return jsonDecode(e)['id'] == id;
      } catch (_) {
        return true;
      }
    });
    await p.setStringList(_historyKey, list);
    watchHistoryRevision.value++;
  }

  Future<void> clearWatchHistory() async {
    final p = await SharedPreferences.getInstance();
    await p.remove(_historyKey);
    watchHistoryRevision.value++;
  }
}

// ════════════════════════════════════════════════════════════════════
//  Models
// ════════════════════════════════════════════════════════════════════

class KdramaCard {
  final int id;
  final String title;
  final String cover;
  final String? label;
  final int episodesCount;
  final String? year;
  /// Raw kisskh type: `TVSeries`, `Movie`, `Anime`, `Hollywood`.
  final String? type;

  const KdramaCard({
    required this.id,
    required this.title,
    required this.cover,
    this.label,
    this.episodesCount = 0,
    this.year,
    this.type,
  });

  factory KdramaCard.fromEngineJson(Map<String, dynamic> json) {
    final typeRaw = (json['type'] as String?)?.trim();
    final labelRaw = (json['label'] as String?)?.trim();
    return KdramaCard(
      id: (json['id'] as num).toInt(),
      title: (json['title'] as String? ?? '').trim(),
      cover: json['cover'] as String? ?? '',
      label: labelRaw == null || labelRaw.isEmpty ? null : labelRaw,
      episodesCount: (json['episodes_count'] as num?)?.toInt() ?? 0,
      year: json['year'] as String?,
      type: typeRaw == null || typeRaw.isEmpty ? null : typeRaw,
    );
  }

  Map<String, dynamic> toEngineJson() => {
        'id': id,
        'title': title,
        'cover': cover,
        if (label != null) 'label': label,
        'episodes_count': episodesCount,
        if (year != null) 'year': year,
        if (type != null) 'type': type,
      };

  KdramaCard copyWith({
    int? id,
    String? title,
    String? cover,
    String? label,
    int? episodesCount,
    String? year,
    String? type,
  }) {
    return KdramaCard(
      id: id ?? this.id,
      title: title ?? this.title,
      cover: cover ?? this.cover,
      label: label ?? this.label,
      episodesCount: episodesCount ?? this.episodesCount,
      year: year ?? this.year,
      type: type ?? this.type,
    );
  }

  /// Home-hero style badge: SERIES / FILM / ANIME / HOLLYWOOD.
  String? get heroMediaBadge {
    switch ((type ?? '').toLowerCase()) {
      case 'tvseries':
        return 'SERIES';
      case 'movie':
        return 'FILM';
      case 'anime':
        return 'ANIME';
      case 'hollywood':
        return 'HOLLYWOOD';
      default:
        return type?.isNotEmpty == true ? type!.toUpperCase() : null;
    }
  }

  /// Home-poster style label: TV / FILM / ANIME / HOLLYWOOD.
  String? get cardMediaLabel {
    switch ((type ?? '').toLowerCase()) {
      case 'tvseries':
        return 'TV';
      case 'movie':
        return 'FILM';
      case 'anime':
        return 'ANIME';
      case 'hollywood':
        return 'HOLLYWOOD';
      default:
        return type?.isNotEmpty == true ? type : null;
    }
  }
}

class KdramaHomeFeed {
  final List<KdramaCard> spotlight;
  final List<KdramaCard> latest;
  final List<KdramaCard> mostViewed;
  final List<KdramaCard> trending;
  final List<KdramaCard> topRated;
  final List<KdramaCard> upcoming;
  final List<KdramaCard> anime;

  const KdramaHomeFeed({
    this.spotlight = const [],
    this.latest = const [],
    this.mostViewed = const [],
    this.trending = const [],
    this.topRated = const [],
    this.upcoming = const [],
    this.anime = const [],
  });

  factory KdramaHomeFeed.fromEngineJson(Map<String, dynamic> json) {
    List<KdramaCard> list(String key) {
      final raw = json[key] as List<dynamic>? ?? const [];
      return raw
          .map((e) => KdramaCard.fromEngineJson(e as Map<String, dynamic>))
          .toList();
    }

    return KdramaHomeFeed(
      spotlight: list('spotlight'),
      latest: list('latest'),
      mostViewed: list('most_viewed'),
      trending: list('trending'),
      topRated: list('top_rated'),
      upcoming: list('upcoming'),
      anime: list('anime'),
    );
  }

  Map<String, dynamic> toEngineJson() => {
        'spotlight': spotlight.map((c) => c.toEngineJson()).toList(),
        'latest': latest.map((c) => c.toEngineJson()).toList(),
        'most_viewed': mostViewed.map((c) => c.toEngineJson()).toList(),
        'trending': trending.map((c) => c.toEngineJson()).toList(),
        'top_rated': topRated.map((c) => c.toEngineJson()).toList(),
        'upcoming': upcoming.map((c) => c.toEngineJson()).toList(),
        'anime': anime.map((c) => c.toEngineJson()).toList(),
      };
}

class KdramaDetails {
  final int id;
  final String title;
  final String description;
  final String cover;
  final String releaseDate;
  final String country;
  final String status;
  final String type;
  final int episodesCount;
  final String? label;
  final List<KdramaEpisode> episodes;

  const KdramaDetails({
    required this.id,
    required this.title,
    required this.description,
    required this.cover,
    required this.releaseDate,
    required this.country,
    required this.status,
    required this.type,
    required this.episodesCount,
    this.label,
    this.episodes = const [],
  });

  factory KdramaDetails.fromEngineJson(Map<String, dynamic> json) {
    final eps = (json['episodes'] as List<dynamic>? ?? const [])
        .map((e) => KdramaEpisode.fromEngineJson(e as Map<String, dynamic>))
        .toList();
    final labelRaw = (json['label'] as String?)?.trim();
    return KdramaDetails(
      id: (json['id'] as num).toInt(),
      title: (json['title'] as String? ?? '').trim(),
      description: (json['description'] as String? ?? '').trim(),
      cover: json['cover'] as String? ?? '',
      releaseDate: json['release_date'] as String? ?? '',
      country: json['country'] as String? ?? '',
      status: json['status'] as String? ?? '',
      type: json['type'] as String? ?? '',
      episodesCount: (json['episodes_count'] as num?)?.toInt() ?? eps.length,
      label: labelRaw == null || labelRaw.isEmpty ? null : labelRaw,
      episodes: eps,
    );
  }

  String? get year => KissKhService.yearFromRelease(releaseDate);

  KdramaCard toCard() => KdramaCard(
        id: id,
        title: title,
        cover: cover,
        label: label,
        episodesCount: episodesCount,
        year: year,
        type: type.isEmpty ? null : type,
      );

  /// Match a watch-history entry to a live episode row (number first — stable
  /// across kisskh API id churn; id is a secondary hint).
  KdramaEpisode? episodeForResume({
    required double episodeNumber,
    int? episodeId,
  }) {
    return KissKhService.matchResumeEpisode(
      episodes: episodes,
      episodeNumber: episodeNumber,
      episodeId: episodeId,
    );
  }
}

class KdramaEpisode {
  final int id;
  final double number;
  final int sub;

  const KdramaEpisode({
    required this.id,
    required this.number,
    this.sub = 0,
  });

  factory KdramaEpisode.fromEngineJson(Map<String, dynamic> json) {
    return KdramaEpisode(
      id: (json['id'] as num).toInt(),
      number: (json['number'] as num).toDouble(),
      sub: (json['sub'] as num?)?.toInt() ?? 0,
    );
  }

  String get displayNumber {
    if (number == number.truncateToDouble()) return number.toInt().toString();
    return number.toString();
  }
}

/// Single page of the `/DramaList/List` Explore endpoint.
class KdramaExplorePage {
  final List<KdramaCard> items;
  final int total;
  final int page;
  final int pageSize;
  const KdramaExplorePage({
    required this.items,
    required this.total,
    required this.page,
    this.pageSize = 40,
  });

  factory KdramaExplorePage.fromEngineJson(Map<String, dynamic> json) {
    final raw = json['items'] as List<dynamic>? ?? const [];
    return KdramaExplorePage(
      items: raw
          .map((e) => KdramaCard.fromEngineJson(e as Map<String, dynamic>))
          .toList(),
      total: (json['total'] as num?)?.toInt() ?? 0,
      page: (json['page'] as num?)?.toInt() ?? 1,
      pageSize: (json['page_size'] as num?)?.toInt() ?? 40,
    );
  }

  bool get hasMore => page * pageSize < total;
}

/// Static lookup tables for the Explore filter chips. Order matches the
/// integer codes consumed by `KissKhService.explore(...)`.
class KissKhExploreFilters {
  static const List<String> types = [
    'All', 'TV Series', 'Movie', 'Anime', 'Hollywood',
  ];
  static const List<String> subtitles = [
    'All', 'English', 'Khmer', 'Indonesian', 'Malay', 'Thai', 'Arabic',
  ];
  static const List<String> countries = [
    'All', 'South Korea', 'Chinese', 'United States', 'Thailand',
    'Philippine', 'Japanese', 'Hong Kong', 'Taiwan',
  ];
  static const List<String> statuses = [
    'All', 'Ongoing', 'Completed', 'Upcoming',
  ];
  static const List<String> orders = [
    // index 0 unused — the API uses 1-based ordering codes.
    '', 'Popular', 'Last Update', 'Release Date',
  ];
}
