part of 'trailer_player_screen.dart';

mixin _TrailerPlayerMenus on State<TrailerPlayerScreen> {
  _TrailerPlayerScreenState get _s => this as _TrailerPlayerScreenState;

  static const List<double> _speedRates = [
    0.5,
    0.75,
    1.0,
    1.25,
    1.5,
    1.75,
    2.0,
  ];

  Future<void> _showSubtitleMenu(BuildContext anchorContext) async {
    if (!_s._ready) return;
    _s._hideTimer?.cancel();
    if (!_s._showControls) setState(() => _s._showControls = true);
    final tracks = _s._streams?.captions ?? const <YoutubeCaptionTrack>[];
    final activeCode = _s._activeCaptionCode;

    if (!mounted) return;
    await PlayerPopupPanel.show(
      context: context,
      title: 'Subtitles',
      leadingIcon: Icons.subtitles_outlined,
      anchorContext: anchorContext,
      maxHeight: 360,
      child: ListView(
        shrinkWrap: true,
        padding: const EdgeInsets.fromLTRB(8, 4, 8, 8),
        children: [
          PlayerPopupListTile(
            label: 'Off',
            selected: activeCode == null,
            onTap: () async {
              PlayerPopupPanel.dismiss();
              await _s._applyCaptionTrack(null);
            },
          ),
          if (tracks.isEmpty)
            const Padding(
              padding: EdgeInsets.fromLTRB(12, 8, 12, 4),
              child: Text(
                'No subtitles available for this trailer.',
                style: TextStyle(color: PlayerPopupTokens.muted, fontSize: 13),
              ),
            )
          else
            for (final track in tracks)
              PlayerPopupListTile(
                label: _flaggedLabel(
                  track.langCode,
                  track.isAutoGenerated
                      ? '${track.langName} (auto)'
                      : track.langName,
                ),
                selected: activeCode == track.langCode,
                onTap: () async {
                  PlayerPopupPanel.dismiss();
                  await _s._applyCaptionTrack(track.langCode);
                },
              ),
        ],
      ),
    );
    if (mounted) _s._startHideTimer();
  }

  Future<void> _showQualityMenu(BuildContext anchorContext) async {
    if (!_s._ready) return;
    _s._hideTimer?.cancel();
    if (!_s._showControls) setState(() => _s._showControls = true);
    final qualities = _s._streams?.qualities ?? const <YoutubeQuality>[];
    final selectedHeight = _s._selectedQualityHeight;

    if (!mounted) return;
    await PlayerPopupPanel.show(
      context: context,
      title: 'Quality',
      leadingIcon: Icons.hd_outlined,
      anchorContext: anchorContext,
      maxHeight: 360,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(12, 12, 12, 14),
        child: qualities.isEmpty
            ? const Text(
                'No quality options for this trailer.',
                style: TextStyle(color: PlayerPopupTokens.muted, fontSize: 13),
              )
            : Wrap(
                spacing: 8,
                runSpacing: 8,
                children: qualities.map((q) {
                  final selected = selectedHeight == q.height;
                  return PlayerPopupOptionChip(
                    label: q.label,
                    selected: selected,
                    onTap: () async {
                      PlayerPopupPanel.dismiss();
                      if (selected) return;
                      await _s._switchQuality(q);
                    },
                  );
                }).toList(),
              ),
      ),
    );
    if (mounted) _s._startHideTimer();
  }

  Future<void> _showSpeedMenu(BuildContext anchorContext) async {
    if (!_s._ready) return;
    _s._hideTimer?.cancel();
    if (!_s._showControls) setState(() => _s._showControls = true);
    final currentRate = _s._playbackRate;

    if (!mounted) return;
    await PlayerPopupPanel.show(
      context: context,
      title: 'Playback speed',
      leadingIcon: Icons.speed_rounded,
      anchorContext: anchorContext,
      maxHeight: 360,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(12, 12, 12, 14),
        child: Wrap(
          spacing: 8,
          runSpacing: 8,
          children: _speedRates.map((rate) {
            final selected = (rate - currentRate).abs() < 0.01;
            return PlayerPopupOptionChip(
              label: '${_formatRate(rate)}x',
              selected: selected,
              onTap: () async {
                PlayerPopupPanel.dismiss();
                await _s._setRate(rate);
              },
            );
          }).toList(),
        ),
      ),
    );
    if (mounted) _s._startHideTimer();
  }

  Future<void> _showPlayerMenu(BuildContext anchorContext) async {
    _s._hideTimer?.cancel();
    if (!_s._showControls) setState(() => _s._showControls = true);
    if (!mounted) return;
    await PlayerPopupPanel.show(
      context: context,
      title: 'Player',
      leadingIcon: Icons.smart_display_outlined,
      anchorContext: anchorContext,
      centered: _s._tvFocus,
      maxHeight: 280,
      child: ListView(
        shrinkWrap: true,
        padding: const EdgeInsets.fromLTRB(10, 10, 10, 12),
        children: [
          const Padding(
            padding: EdgeInsets.fromLTRB(4, 0, 4, 8),
            child: Text(
              'Built-in',
              style: TextStyle(
                color: PlayerPopupTokens.muted,
                fontSize: 12,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          PlayerPopupOptionChip(
            label: 'Forja trailer',
            selected: true,
            expanded: true,
            onTap: PlayerPopupPanel.dismiss,
          ),
          const SizedBox(height: 14),
          const Padding(
            padding: EdgeInsets.fromLTRB(4, 0, 4, 8),
            child: Text(
              'External app',
              style: TextStyle(
                color: PlayerPopupTokens.muted,
                fontSize: 12,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          PlayerPopupOptionChip(
            label: 'YouTube',
            selected: false,
            expanded: true,
            onTap: () async {
              PlayerPopupPanel.dismiss();
              await _s._openInYouTube();
            },
          ),
        ],
      ),
    );
    if (mounted) {
      _s._startHideTimer();
      if (_s._tvFocus) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (!mounted || !_s._playerMenuFocus.canRequestFocus) return;
          _s._playerMenuFocus.requestFocus();
        });
      }
    }
  }

  Future<void> _openInYouTube() async {
    final uri = Uri.parse(_s._trailer.youtubeUrl);
    final ok = await launchUrl(uri, mode: LaunchMode.externalApplication);
    if (!ok && mounted) {
      ForjaToast.show(
        'Could not open YouTube',
        kind: ForjaToastKind.error,
        duration: const Duration(seconds: 3),
      );
    }
  }

  String _flaggedLabel(String? code, String name) {
    final flag = _flagForLang(code);
    if (flag.isEmpty) return name;
    return '$flag  $name';
  }

  String _flagForLang(String? code) {
    if (code == null || code.trim().isEmpty) return '';
    final raw = code.trim().toLowerCase();
    final direct = StreamProviderDisplay.flagForCountry(raw);
    if (direct.isNotEmpty) return direct;
    final base = raw.split(RegExp(r'[-_]')).first;
    final fromBase = StreamProviderDisplay.flagForCountry(base);
    if (fromBase.isNotEmpty) return fromBase;
    return StreamProviderDisplay.flagsForText(raw);
  }

  String _formatRate(double rate) {
    if (rate == rate.roundToDouble()) return rate.toStringAsFixed(0);
    return rate.toStringAsFixed(2).replaceAll(RegExp(r'\.?0+$'), '');
  }
}
