[package]
name = "forja-torrent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true }
futures-util = "0.3"
librqbit = { version = "9.0.0-rc.0", default-features = false, features = ["rust-tls"] }
forja-utils = { path = "../forja-utils" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "net"] }
tokio-util = { version = "0.7", features = ["io"] }
urlencoding = "2"
