[package]
name = "forja-torrent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
librqbit = { version = "9.0.0-rc.0", default-features = false, features = ["rust-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
