[package]
name = "webstreamr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
utils = { path = "../utils" }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rayon = "1"
scraper = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
aes = { workspace = true }
aes-gcm = { workspace = true }
cbc = { workspace = true }
sha2 = { workspace = true }
hex = "0.4"
base64 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
wiremock = "0.6"
