#!/usr/bin/env bash
# List public barrel exports for RFC-106 G14-A shim map.
# Usage: scripts/foundation_export_inventory.sh [out_path]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/docs/rfc/106-export-inventory.txt}"

FOUNDATION="$ROOT/apps/forja/lib/shared/foundation/foundation.dart"
PRIMITIVES="$ROOT/apps/forja/lib/shared/foundation/primitives/primitives.dart"

mkdir -p "$(dirname "$OUT")"

{
  echo "# RFC-106 export inventory"
  echo "# Generated by scripts/foundation_export_inventory.sh"
  echo "# Do not hand-edit; re-run the script after barrel changes."
  echo "#"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo

  echo "## foundation.dart"
  echo "# $FOUNDATION"
  rg '^export ' "$FOUNDATION" | sed 's/^export //; s/;$//' | sort
  echo
  echo "# count: $(rg -c '^export ' "$FOUNDATION" || true)"
  echo

  echo "## primitives.dart"
  echo "# $PRIMITIVES"
  rg '^export ' "$PRIMITIVES" | sed 's/^export //; s/;$//' | sort
  echo
  echo "# count: $(rg -c '^export ' "$PRIMITIVES" || true)"
} >"$OUT"

echo "Wrote $OUT"
