#!/usr/bin/env bash
# List public package barrel exports (RFC-106).
# Usage: scripts/foundation_export_inventory.sh [out_path]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/docs/rfc/106-export-inventory.txt}"
PKG="$ROOT/packages/forja_foundation/lib"

mkdir -p "$(dirname "$OUT")"

{
  echo "# RFC-106 export inventory"
  echo "# Generated by scripts/foundation_export_inventory.sh"
  echo "# Do not hand-edit; re-run the script after barrel changes."
  echo "#"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo

  for name in forja_foundation.dart forja_foundation_primitives.dart forja_foundation_kit.dart; do
    file="$PKG/$name"
    echo "## $name"
    echo "# $file"
    rg '^export ' "$file" | sed 's/^export //; s/;$//' | sort
    echo
    echo "# count: $(rg -c '^export ' "$file" || true)"
    echo
  done
} >"$OUT"

echo "Wrote $OUT"
