[package]
name = "engine-js"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "audit-engine-plugins"
path = "src/bin/audit_engine_plugins.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
reqwest = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
aes = { workspace = true }
aes-gcm = { workspace = true }
cbc = { workspace = true }
md-5 = { workspace = true }
sha1 = "0.10"
hmac = "0.12"
scrypt = "0.11"
flate2 = "1"
utils = { path = "../utils" }
kisskh = { path = "../kisskh" }
rquickjs = { version = "0.9", features = ["futures", "parallel", "macro", "bindgen"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
