import 'dart:isolate';

import 'package:flutter/foundation.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt_explode;

/// One closed-caption track as a direct WebVTT URL.
class YoutubeCaptionTrack {
  final String url;
  final String langCode;
  final String langName;
  final bool isAutoGenerated;

  const YoutubeCaptionTrack({
    required this.url,
    required this.langCode,
    required this.langName,
    this.isAutoGenerated = false,
  });
}

/// One selectable video-only quality. Shares [YoutubeResolvedStreams.audioUrl].
class YoutubeQuality {
  final int height;
  final String videoUrl;

  const YoutubeQuality({required this.height, required this.videoUrl});

  String get label => '${height}p';
}

/// Resolved playable URLs for a single YouTube video.
class YoutubeResolvedStreams {
  /// Default open URL. Prefer muxed progressive (A+V) when YouTube offers it;
  /// otherwise a video-only adaptive URL that needs [audioUrl].
  final String? playUrl;

  /// Resolution height of [playUrl] (muxed or adaptive pick).
  final int? playHeight;

  /// Separate AAC for video-only URLs in [qualities] (and adaptive [playUrl]).
  /// Null when [playUrl] is muxed-only and no adaptive ladder exists.
  final String? audioUrl;

  final String? title;
  final String? thumbnailUrl;
  final int? durationSeconds;

  /// Video-only qualities (highest first). H.264 ≤1080p + VP9 above; no AV1.
  final List<YoutubeQuality> qualities;

  /// WebVTT caption tracks (empty when none / fetch failed).
  final List<YoutubeCaptionTrack> captions;

  const YoutubeResolvedStreams({
    this.playUrl,
    this.playHeight,
    this.audioUrl,
    this.title,
    this.thumbnailUrl,
    this.durationSeconds,
    this.qualities = const [],
    this.captions = const [],
  });

  bool get hasPlayable => playUrl != null && playUrl!.isNotEmpty;
}

class _ResolvedCacheEntry {
  final YoutubeResolvedStreams streams;
  final DateTime at;
  const _ResolvedCacheEntry(this.streams, this.at);
}

/// Resolve YouTube video ids to googlevideo URLs (Debrify path).
///
/// No search / InnerTube — stream extraction only via youtube_explode.
class YoutubeStreamService {
  YoutubeStreamService._();

  static const int defaultMaxHeight = 1080;
  static const Duration _resolveCacheTtl = Duration(minutes: 10);

  static final Map<String, _ResolvedCacheEntry> _resolveCache = {};
  static final Map<String, Future<YoutubeResolvedStreams?>> _resolveInFlight =
      {};

  /// Resolve [videoId] into playable URLs.
  ///
  /// Prefer ANDROID_VR client (mpv-friendly googlevideo URLs). Cap default
  /// quality at [maxHeightOverride] or [defaultMaxHeight]. When [withCaptions]
  /// is true, also fetch WebVTT tracks.
  static Future<YoutubeResolvedStreams?> resolveStreams(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
  }) {
    final key = _resolveKey(videoId, maxHeightOverride, withCaptions);
    final cached = _resolveCache[key];
    if (cached != null &&
        DateTime.now().difference(cached.at) < _resolveCacheTtl) {
      return Future.value(cached.streams);
    }
    final inFlight = _resolveInFlight[key];
    if (inFlight != null) return inFlight;
    final future = _resolveUncached(
      videoId,
      maxHeightOverride: maxHeightOverride,
      withCaptions: withCaptions,
    );
    _resolveInFlight[key] = future;
    return future.whenComplete(() => _resolveInFlight.remove(key));
  }

  static String _resolveKey(
    String videoId,
    int? maxHeightOverride,
    bool withCaptions,
  ) {
    final base = maxHeightOverride == null
        ? videoId
        : '$videoId#h$maxHeightOverride';
    return withCaptions ? '$base#cc' : base;
  }

  static Future<YoutubeResolvedStreams?> _resolveUncached(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
  }) async {
    final maxHeight = maxHeightOverride ?? defaultMaxHeight;
    try {
      final streams = await Isolate.run(
        () => _resolveStreamsBlocking(videoId, maxHeight, withCaptions),
      );
      if (streams != null) {
        _resolveCache.removeWhere(
          (_, e) => DateTime.now().difference(e.at) >= _resolveCacheTtl,
        );
        _resolveCache[_resolveKey(videoId, maxHeightOverride, withCaptions)] =
            _ResolvedCacheEntry(streams, DateTime.now());
      }
      return streams;
    } catch (e) {
      debugPrint('YoutubeStreamService: resolve failed for $videoId — $e');
      return null;
    }
  }

  static Future<YoutubeResolvedStreams?> _resolveStreamsBlocking(
    String videoId,
    int maxHeight,
    bool withCaptions,
  ) async {
    final yt = yt_explode.YoutubeExplode();
    try {
      yt_explode.StreamManifest manifest;
      try {
        manifest = await yt.videos.streamsClient.getManifest(
          videoId,
          ytClients: [yt_explode.YoutubeApiClient.androidVr],
        );
      } catch (_) {
        manifest = await yt.videos.streamsClient.getManifest(videoId);
      }

      final muxed = manifest.muxed.toList()
        ..sort(
          (a, b) =>
              b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
        );
      final muxedMp4 =
          muxed.where((s) => s.container.name.toLowerCase() == 'mp4');
      final bestMuxedStream =
          muxedMp4.isNotEmpty ? muxedMp4.first : (muxed.isNotEmpty ? muxed.first : null);
      final bestMuxed = bestMuxedStream?.url.toString();

      bool isAvc(String c) => c.toLowerCase().contains('avc');
      bool isVp9(String c) {
        final l = c.toLowerCase();
        return l.contains('vp9') || l.contains('vp09');
      }

      String? playUrl;
      int? playHeight;
      String? audioUrl;
      final qualities = <YoutubeQuality>[];
      final videoOnly = manifest.videoOnly
          .where((s) => isAvc(s.videoCodec) || isVp9(s.videoCodec))
          .toList();
      final audioStreams = manifest.audioOnly
          .where((s) => s.container.name.toLowerCase() == 'mp4')
          .toList();
      if (videoOnly.isNotEmpty && audioStreams.isNotEmpty) {
        videoOnly.sort((a, b) {
          final byHeight =
              b.videoResolution.height.compareTo(a.videoResolution.height);
          if (byHeight != 0) return byHeight;
          final aAvc = isAvc(a.videoCodec);
          final bAvc = isAvc(b.videoCodec);
          if (aAvc == bAvc) return 0;
          return aAvc ? -1 : 1;
        });

        final seenHeights = <int>{};
        for (final s in videoOnly) {
          final h = s.videoResolution.height;
          if (!seenHeights.add(h)) continue;
          qualities.add(YoutubeQuality(height: h, videoUrl: s.url.toString()));
        }

        audioStreams.sort(
          (a, b) =>
              b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
        );
        audioUrl = audioStreams.first.url.toString();
      }

      // Muxed first — baked-in audio (adaptive video-only was silent when
      // mpv audio-file failed to attach). Keep [audioUrl]/[qualities] for HD.
      if (bestMuxed != null) {
        playUrl = bestMuxed;
        playHeight = bestMuxedStream?.videoResolution.height;
      } else if (qualities.isNotEmpty) {
        final atOrBelow =
            qualities.where((q) => q.height <= maxHeight).toList();
        final pick =
            atOrBelow.isNotEmpty ? atOrBelow.first : qualities.last;
        playUrl = pick.videoUrl;
        playHeight = pick.height;
      }
      if (playUrl == null) return null;

      String? title;
      String? thumb;
      int? duration;
      final captions = <YoutubeCaptionTrack>[];
      await Future.wait([
        () async {
          try {
            final video = await yt.videos.get(videoId);
            title = video.title;
            thumb = video.thumbnails.highResUrl;
            duration = video.duration?.inSeconds;
          } catch (_) {}
        }(),
        () async {
          if (!withCaptions) return;
          try {
            final ccManifest = await yt.videos.closedCaptions.getManifest(
              videoId,
              formats: const [yt_explode.ClosedCaptionFormat.vtt],
            );
            for (final t in ccManifest.tracks) {
              captions.add(
                YoutubeCaptionTrack(
                  url: t.url.toString(),
                  langCode: t.language.code,
                  langName: t.language.name.isNotEmpty
                      ? t.language.name
                      : t.language.code,
                  isAutoGenerated: t.isAutoGenerated,
                ),
              );
            }
          } catch (_) {}
        }(),
      ]);

      return YoutubeResolvedStreams(
        playUrl: playUrl,
        playHeight: playHeight,
        audioUrl: audioUrl,
        title: title,
        thumbnailUrl: thumb,
        durationSeconds: duration,
        qualities: qualities,
        captions: captions,
      );
    } finally {
      try {
        yt.close();
      } catch (_) {}
    }
  }
}
