import 'dart:async';
import 'dart:isolate';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt_explode;

/// One closed-caption track as a direct WebVTT URL.
class YoutubeCaptionTrack {
  final String url;
  final String langCode;
  final String langName;
  final bool isAutoGenerated;

  const YoutubeCaptionTrack({
    required this.url,
    required this.langCode,
    required this.langName,
    this.isAutoGenerated = false,
  });
}

/// One selectable video-only quality. Shares [YoutubeResolvedStreams.audioUrl].
class YoutubeQuality {
  final int height;
  final String videoUrl;
  final int contentLength;

  const YoutubeQuality({
    required this.height,
    required this.videoUrl,
    this.contentLength = 0,
  });

  String get label => '${height}p';
}

/// Resolved playable URLs for a single YouTube video.
class YoutubeResolvedStreams {
  /// Adaptive video-only (itag 137 = 1080p AVC) or muxed progressive fallback.
  final String? playUrl;

  final int? playHeight;

  /// AAC (itag 140). Bound via mpv `audio-file` before open. Null if muxed.
  final String? audioUrl;

  final int audioContentLength;

  /// Muxed progressive (A+V) — typically ≤360p. Fallback when adaptive stalls.
  final String? muxedUrl;

  final int? muxedHeight;

  final String? title;
  final String? thumbnailUrl;
  final int? durationSeconds;

  /// Video-only heights, highest first. AVC preferred at a given height; no AV1.
  final List<YoutubeQuality> qualities;

  final List<YoutubeCaptionTrack> captions;

  const YoutubeResolvedStreams({
    this.playUrl,
    this.playHeight,
    this.audioUrl,
    this.audioContentLength = 0,
    this.muxedUrl,
    this.muxedHeight,
    this.title,
    this.thumbnailUrl,
    this.durationSeconds,
    this.qualities = const [],
    this.captions = const [],
  });

  bool get hasPlayable => playUrl != null && playUrl!.isNotEmpty;

  YoutubeResolvedStreams copyWith({
    String? playUrl,
    int? playHeight,
    String? audioUrl,
    int? audioContentLength,
    String? muxedUrl,
    int? muxedHeight,
    String? title,
    String? thumbnailUrl,
    int? durationSeconds,
    List<YoutubeQuality>? qualities,
    List<YoutubeCaptionTrack>? captions,
  }) {
    return YoutubeResolvedStreams(
      playUrl: playUrl ?? this.playUrl,
      playHeight: playHeight ?? this.playHeight,
      audioUrl: audioUrl ?? this.audioUrl,
      audioContentLength: audioContentLength ?? this.audioContentLength,
      muxedUrl: muxedUrl ?? this.muxedUrl,
      muxedHeight: muxedHeight ?? this.muxedHeight,
      title: title ?? this.title,
      thumbnailUrl: thumbnailUrl ?? this.thumbnailUrl,
      durationSeconds: durationSeconds ?? this.durationSeconds,
      qualities: qualities ?? this.qualities,
      captions: captions ?? this.captions,
    );
  }
}

class _ResolvedCacheEntry {
  final YoutubeResolvedStreams streams;
  final DateTime at;
  const _ResolvedCacheEntry(this.streams, this.at);
}

({String? url, int? height}) _bestProgressiveMuxed(
  yt_explode.StreamManifest manifest,
) {
  final muxed = manifest.muxed.toList()
    ..sort(
      (a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
    );
  final muxedMp4 = muxed.where((s) => s.container.name.toLowerCase() == 'mp4');
  final best = muxedMp4.isNotEmpty
      ? muxedMp4.first
      : (muxed.isNotEmpty ? muxed.first : null);
  return (url: best?.url.toString(), height: best?.videoResolution.height);
}

/// explode getManifest HEADs streams.first (itag 137) → 403 and drops the client.
class _SkipHeadYoutubeClient extends yt_explode.YoutubeHttpClient {
  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) async {
    if (request.method == 'HEAD') {
      return http.StreamedResponse(
        const Stream<List<int>>.empty(),
        200,
        contentLength: 1,
        request: request,
      );
    }
    return super.send(request);
  }
}

/// Resolve YouTube video ids to googlevideo DASH (video + AAC).
class YoutubeStreamService {
  YoutubeStreamService._();

  static const int defaultMaxHeight = 1080;
  static const Duration _resolveCacheTtl = Duration(minutes: 10);

  static final Map<String, _ResolvedCacheEntry> _resolveCache = {};
  static final Map<String, Future<YoutubeResolvedStreams?>> _resolveInFlight =
      {};
  static final Map<String, Future<List<YoutubeCaptionTrack>>> _captionsInFlight =
      {};

  static void prefetch(Iterable<String> videoIds, {int limit = 3}) {
    var n = 0;
    for (final id in videoIds) {
      if (id.isEmpty) continue;
      if (n >= limit) break;
      n++;
      unawaited(resolveStreams(id));
    }
  }

  /// Adaptive ≤[maxHeightOverride] (itag 137 + AAC). TV first, then sdkless/ios.
  static Future<YoutubeResolvedStreams?> resolveStreams(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
    bool withMetadata = false,
    bool forceRefresh = false,
  }) {
    final key = _resolveKey(
      videoId,
      maxHeightOverride,
      withCaptions: withCaptions,
      withMetadata: withMetadata,
    );
    if (forceRefresh) {
      _resolveCache.remove(key);
      _resolveInFlight.remove(key);
    } else {
      final cached = _resolveCache[key];
      if (cached != null &&
          DateTime.now().difference(cached.at) < _resolveCacheTtl) {
        return Future.value(cached.streams);
      }
      final inFlight = _resolveInFlight[key];
      if (inFlight != null) return inFlight;
    }
    final future = _resolveUncached(
      videoId,
      maxHeightOverride: maxHeightOverride,
      withCaptions: withCaptions,
      withMetadata: withMetadata,
    );
    _resolveInFlight[key] = future;
    return future.whenComplete(() => _resolveInFlight.remove(key));
  }

  static Future<List<YoutubeCaptionTrack>> fetchCaptions(String videoId) {
    final inFlight = _captionsInFlight[videoId];
    if (inFlight != null) return inFlight;
    final future = _fetchCaptionsUncached(videoId);
    _captionsInFlight[videoId] = future;
    return future.whenComplete(() => _captionsInFlight.remove(videoId));
  }

  static String _resolveKey(
    String videoId,
    int? maxHeightOverride, {
    required bool withCaptions,
    required bool withMetadata,
  }) {
    final base = maxHeightOverride == null
        ? videoId
        : '$videoId#h$maxHeightOverride';
    final cc = withCaptions ? '#cc' : '';
    final meta = withMetadata ? '#meta' : '';
    return '$base$cc$meta';
  }

  static Future<YoutubeResolvedStreams?> _resolveUncached(
    String videoId, {
    int? maxHeightOverride,
    bool withCaptions = false,
    bool withMetadata = false,
  }) async {
    final maxHeight = maxHeightOverride ?? defaultMaxHeight;
    try {
      final streams = await Isolate.run(
        () => _resolveStreamsBlocking(
          videoId,
          maxHeight,
          withCaptions,
          withMetadata,
        ),
      );
      if (streams != null) {
        _resolveCache.removeWhere(
          (_, e) => DateTime.now().difference(e.at) >= _resolveCacheTtl,
        );
        _resolveCache[_resolveKey(
          videoId,
          maxHeightOverride,
          withCaptions: withCaptions,
          withMetadata: withMetadata,
        )] = _ResolvedCacheEntry(streams, DateTime.now());
      }
      return streams;
    } catch (e, st) {
      debugPrint('YoutubeStreamService: resolve failed for $videoId — $e\n$st');
      rethrow;
    }
  }

  static Future<List<YoutubeCaptionTrack>> _fetchCaptionsUncached(
    String videoId,
  ) async {
    try {
      return await Isolate.run(() => _fetchCaptionsBlocking(videoId));
    } catch (e) {
      debugPrint('YoutubeStreamService: captions failed for $videoId — $e');
      return const [];
    }
  }

  static Future<List<YoutubeCaptionTrack>> _fetchCaptionsBlocking(
    String videoId,
  ) async {
    final yt = yt_explode.YoutubeExplode();
    try {
      return await _captionsOnYt(yt, videoId);
    } finally {
      try {
        yt.close();
      } catch (_) {}
    }
  }

  static Future<YoutubeResolvedStreams?> _resolveStreamsBlocking(
    String videoId,
    int maxHeight,
    bool withCaptions,
    bool withMetadata,
  ) async {
    final http = _SkipHeadYoutubeClient();
    final yt = yt_explode.YoutubeExplode(httpClient: http);
    try {
      final resolved = await _tryAdaptive(yt, videoId, maxHeight);
      if (resolved == null || !resolved.hasPlayable) return null;
      if (!withMetadata && !withCaptions) return resolved;

      String? title = resolved.title;
      String? thumb = resolved.thumbnailUrl;
      int? duration = resolved.durationSeconds;
      var captions = resolved.captions;
      await Future.wait([
        () async {
          if (!withMetadata) return;
          try {
            final video = await yt.videos.get(videoId);
            title = video.title;
            thumb = video.thumbnails.highResUrl;
            duration = video.duration?.inSeconds;
          } catch (_) {}
        }(),
        () async {
          if (!withCaptions) return;
          captions = await _captionsOnYt(yt, videoId);
        }(),
      ]);
      return resolved.copyWith(
        title: title,
        thumbnailUrl: thumb,
        durationSeconds: duration,
        captions: captions,
      );
    } finally {
      try {
        yt.close();
      } catch (_) {}
    }
  }

  static Future<YoutubeResolvedStreams?> _tryAdaptive(
    yt_explode.YoutubeExplode yt,
    String videoId,
    int maxHeight,
  ) async {
    yt_explode.StreamManifest? manifest;
    final clientAttempts = <List<yt_explode.YoutubeApiClient>?>[
      [yt_explode.YoutubeApiClient.tv],
      [yt_explode.YoutubeApiClient.androidSdkless],
      [yt_explode.YoutubeApiClient.ios],
      null,
    ];
    Object? lastError;
    for (final clients in clientAttempts) {
      try {
        final m = clients == null
            ? await yt.videos.streamsClient.getManifest(videoId)
            : await yt.videos.streamsClient.getManifest(
                videoId,
                ytClients: clients,
              );
        if (m.muxed.isNotEmpty || m.videoOnly.isNotEmpty) {
          manifest = m;
          break;
        }
      } catch (e) {
        lastError = e;
      }
    }
    if (manifest == null) {
      throw lastError ?? StateError('No YouTube streams for $videoId');
    }

    final muxed = _bestProgressiveMuxed(manifest);
    final bestMuxed = muxed.url;
    final bestMuxedHeight = muxed.height;

    bool isAvc(String c) => c.toLowerCase().contains('avc');
    bool isVp9(String c) {
      final l = c.toLowerCase();
      return l.contains('vp9') || l.contains('vp09');
    }

    String? playUrl;
    int? playHeight;
    String? audioUrl;
    final qualities = <YoutubeQuality>[];
    final videoOnly = manifest.videoOnly
        .where((s) {
          final c = s.videoCodec.toLowerCase();
          if (c.contains('av01') || c.contains('av1')) return false;
          return isAvc(s.videoCodec) || isVp9(s.videoCodec);
        })
        .toList();
    final audioMp4 = manifest.audioOnly
        .where((s) => s.container.name.toLowerCase() == 'mp4')
        .toList();
    final audio140 = audioMp4.where((s) => s.tag == 140).toList();
    final audioStreams = audio140.isNotEmpty ? audio140 : audioMp4;
    if (videoOnly.isNotEmpty && audioStreams.isNotEmpty) {
      videoOnly.sort((a, b) {
        final byHeight =
            b.videoResolution.height.compareTo(a.videoResolution.height);
        if (byHeight != 0) return byHeight;
        final aAvc = isAvc(a.videoCodec);
        final bAvc = isAvc(b.videoCodec);
        if (aAvc == bAvc) return 0;
        return aAvc ? -1 : 1;
      });

      final seenHeights = <int>{};
      for (final s in videoOnly) {
        final h = s.videoResolution.height;
        if (!seenHeights.add(h)) continue;
        qualities.add(
          YoutubeQuality(
            height: h,
            videoUrl: s.url.toString(),
            contentLength: s.size.totalBytes,
          ),
        );
      }

      audioStreams.sort(
        (a, b) => b.bitrate.bitsPerSecond.compareTo(a.bitrate.bitsPerSecond),
      );
      audioUrl = audioStreams.first.url.toString();
    }

    if (qualities.isNotEmpty && audioUrl != null) {
      final atOrBelow = qualities.where((q) => q.height <= maxHeight).toList();
      final pick = atOrBelow.isNotEmpty ? atOrBelow.first : qualities.first;
      playUrl = pick.videoUrl;
      playHeight = pick.height;
      // Isolate.run — debugPrint often never reaches the Flutter console.
      print(
        'YoutubeStreamService: DASH ${pick.height}p + AAC '
        '(${qualities.length} rungs, muxed=${bestMuxedHeight ?? 0}p)',
      );
    } else if (bestMuxed != null) {
      playUrl = bestMuxed;
      playHeight = bestMuxedHeight;
    }
    if (playUrl == null) return null;

    return YoutubeResolvedStreams(
      playUrl: playUrl,
      playHeight: playHeight,
      audioUrl: audioUrl,
      audioContentLength: audioUrl == null
          ? 0
          : (audioStreams.isNotEmpty ? audioStreams.first.size.totalBytes : 0),
      muxedUrl: bestMuxed,
      muxedHeight: bestMuxedHeight,
      qualities: qualities,
    );
  }

  static Future<List<YoutubeCaptionTrack>> _captionsOnYt(
    yt_explode.YoutubeExplode yt,
    String videoId,
  ) async {
    try {
      final ccManifest = await yt.videos.closedCaptions.getManifest(
        videoId,
        formats: const [yt_explode.ClosedCaptionFormat.vtt],
      );
      return [
        for (final t in ccManifest.tracks)
          YoutubeCaptionTrack(
            url: t.url.toString(),
            langCode: t.language.code,
            langName: t.language.name.isNotEmpty
                ? t.language.name
                : t.language.code,
            isAutoGenerated: t.isAutoGenerated,
          ),
      ];
    } catch (_) {
      return const [];
    }
  }
}
