name: forja_rust
description: Dart FFI bindings to the Forja Rust engine
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  ffi: ^2.1.4
  forja_core:
    path: ../forja_core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  forja_api:
    path: ../forja_api

flutter:
  uses-material-design: true
